import stasiunCicalengka from "../assets/visualisasi_08.png";
import stasiunCicalengka_article_word from "../assets/article_word/StasiunCicalengka.docx";

const articleData = [
  {
    id: 1,
    name: "Stasiun Cicalengka",
    thumbnail: stasiunCicalengka,
    typePage: "article",
    category: "Sejarah",
    docxFile: stasiunCicalengka_article_word,
    position: [-6.982669, 107.833952],
  },
  {
    id: 2,
    name: "Dokter Gofar",
    thumbnail: stasiunCicalengka,
    typePage: "article",
    category: "Budaya",
    docxFile: stasiunCicalengka_article_word,
    position: [-6.985864, 107.83709],
  },
  {
    id: 3,
    name: "Koramil",
    thumbnail: stasiunCicalengka,
    typePage: "article",
    category: "Budaya",
    docxFile: stasiunCicalengka_article_word,
    position: [-6.981174, 107.833728],
  },
  {
    id: 4,
    name: "Alun - Alun",
    thumbnail: stasiunCicalengka,
    typePage: "article",
    category: "Budaya",
    docxFile: stasiunCicalengka_article_word,
    position: [-6.98752, 107.839432],
  },
  {
    id: 5,
    name: "Menara Sereh",
    thumbnail: stasiunCicalengka,
    typePage: "article",
    category: "Budaya",
    docxFile: stasiunCicalengka_article_word,
    position: [-6.968903, 107.854002],
  },
  {
    id: 6,
    name: "SDN 8 Cicalengka",
    thumbnail: stasiunCicalengka,
    typePage: "article",
    category: "Budaya",
    docxFile: stasiunCicalengka_article_word,
    position: [-6.986566, 107.838367],
  },
  {
    id: 8,
    name: "Masjid Agung",
    thumbnail: stasiunCicalengka,
    typePage: "article",
    category: "Budaya",
    docxFile: stasiunCicalengka_article_word,
    position: [-6.987018, 107.838862],
  },
  {
    id: 9,
    name: "Curug Cinulang",
    thumbnail: stasiunCicalengka,
    typePage: "article",
    category: "Budaya",
    docxFile: stasiunCicalengka_article_word,
    position: [-6.962932, 107.881608],
  },
  {
    id: 11,
    name: "Penjara Umum Tjitjalengka",
    thumbnail: stasiunCicalengka,
    typePage: "article",
    category: "Sejarah",
    docxFile: stasiunCicalengka_article_word,
    position: [-6.9870771642114855, 107.84039449984857],
  },
  {
    id: 12,
    name: "Gereja Santo Antonius",
    thumbnail: stasiunCicalengka,
    typePage: "article",
    category: "Sejarah",
    docxFile: stasiunCicalengka_article_word,
    position: [-6.988665890977238, 107.84006039753635],
  },
];

export default articleData;
